name: edubayo
favicon: null
layout_spectrum: 1
typography_spectrum: 0.36222
title: Edu Bayo - Blog persoinal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5931367676239461
  lightness: 0.043620408745482564
  saturation: 0.44461847515776753
  rhythmicContrast: 0.5
purpose: []
